### ISSUE TITLE
midi-out support [sf#11]

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/blue#11]
a module for sending out mididata to external synthsizers.
a module like the PianoRoll for sending mididata (With
the opcode 'noteondur')to external synthesizers.  Maybe
an extension of this module could be the sending of
controller data -for controlling brightness for
example, or panning- by drawing lines?
With the present PianoRoll i can't get the right
resolution in octaves, this module would make it much
simpler.

**Comment by tjingboem** [comment]
using Blue atm also for sending notes and CCs to AdsynthSubFX, i think this issue can be closed. 
I was thinking about integrating CC Automation Lines inside the PianoRoll - but, as i found out, it is more generic to have a separate Midi CC controller for this. 
![midicontrol](https://user-images.githubusercontent.com/6670911/46418039-387c6e00-c72b-11e8-994d-fcb96b06d018.png)

This instrument can be used parallel with the PianoRoll  but also other Objects like JMask etc. on a different Layer:
![midi2](https://user-images.githubusercontent.com/6670911/46418342-e1c36400-c72b-11e8-9e79-5dcb1ea29f9f.png)

Here, the PianoRoll and JMask is sending midi data to the midi output.

As far as i am concerned (because this issue was originally mine), this issue can be closed.

**Comment by kunstmusik** [comment]
Thanks for feedback on this issue, I will close it now.
