### ISSUE TITLE
copying "file selector" in synth builder, clone has static value

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#251]
If I create a synth with a file selector, then copy paste it into the same synth to create an additional "bank", the new file selector will have a static value even tho it appears to accept a new value.

**Comment by kunstmusik** [comment]
The issue here was that StringChannels were not appropriately handled for when BSBFIleSelectors were serialized with the new copy holding a reference to the older one's channel.  I audited the code and the problem was limited to BSBFileSelector.  This is now fixed and will be available in 2.6.0. 

Thanks!
steven
