### ISSUE TITLE
[Feature Request] Implement ability to open .blue files directly

### ISSUE THREAD

**Issue by ainola** [kunstmusik/blue#292]
For a more complete desktop integration, the ability to directly open a file with Blue would be excellent. This would allow for desktop integration: Clicking on .blue files to open in Blue.

**Comment by kunstmusik** [comment]
I managed to get this working for Windows and Linux, but after a couple of hours experimenting on OSX using an OpenFilesHandler and other tricks, I was unable to get it working.  I also found that trying to use the com.apple.eawt classes for FileHandler seemed to throw off whatever the NetBeans platform was itself doing and would thus break the actions for Help and Quit.  

I am going to mark this item complete as it is at least working for Windows and Linux.  If this issue was for OSX, please file another ticket specifically for that platform and I can take a look again at another time. 

Thanks!
steven
