### ISSUE TITLE
change File Selector to accept input with its relative path

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#320]
(what more can i say?)

**Comment by kunstmusik** [comment]
I think I need more information.  From our email exchange on the Blue mailing list, I saw that the request seemed a bit different from what I'm reading in this issue's title.  How the BSB file selector currently works is:

1. Internally it keeps a String that represents the file's path.  If the file is located within the folder or in a subfolder of the current project, the reference is saved as a relative path.  If the file is located elsewhere, it is maintained as an absolute path.  The reason for this is so that projects remain portable and if they are moved the file paths can be resolved relative to the project. Also, any generated CSD is done within the same folder as the .blue project, so relative paths generated into the CSD will continue to work even if the CSD and project folder are moved. 
2. The user interface reflects whether the file path is relative or absolute according to the above rule. 
3. When BSB goes to generate values for the CSD to send to Csound, it uses the stored path (absolute or relative). 

There are two aspects that I need clarification.  Is this issue asking to have an option to always use relative or absolute paths for both showing to the user as well as when generating output?

I could imagine having an option for the file selector that determines how the reference is stored and shown with the following options:

1. Default - the current Blue behavior
2. Relative - always store by relative path
3. Absolute - always store by absolute path

**Comment by kunstmusik** [comment]
Closing as @tjingboem agreed it is okay. :)
