### ISSUE TITLE
copy and move Automation Line Points together with SoundObject

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#330]
- ability to copy SoundObjects with their Automation Line Points
- ability to move SoundObjects with their Automation Line Points

i do not know exactly what could be the best system how to "attach" Automation Line Points to a SoundObject.
What i do atm is to make an ALPs for all the ALs at the start and at the end of the SoundObject so that they are "connected" to that SoundObject. Stretching is also possible this way, because the beginnings and the ending Points scale with the SoundObject.

Copying them all is not possible this way however.

(perhaps it is an idea to check out on how this is done in Ardour?)

**Comment by kunstmusik** [comment]
I just checked Ardour 4.7 and it actually has the same behavior as Blue where when you move the object, only the points contained within the same time range are moved and no new points are introduced. 

There's sort of a disconnect between concepts here I think.  Automations are really associated with a parameter over time, rather than an individual object, even if it is used in this manner. 

I am unsure about copying/pasting as I just tried something and it killed the Linux VM I was using. Copying/pasting just an object into another layer did nothing for automations though in Ardour, copying just the region.  

Just to clarify, it seems like we can move sound objects and their line points already. It's just that start/end points are not created, yes?  

I will have to check other software to see what other approaches are taken.

For the start/end points issue, because I would always want to automatically adding points, what do you think about if I added an action that would add the points.  For example, either by menu option, keyboard shortcut, or popup menu option, you could select a few objects, hit the short cut to create start/end automation points, then drag from there.  I think that could be fairly easy to use, yes?

**Comment by tjingboem** [comment]
i think it would be a good idea to set automatically start and end point for selected SoundObjects! That would solve the issue of moving very well...

About Ardour: mmm, that's perhaps another reason why i will not use Ardour. My experience with DAWs are Cubase and Nuendo. This is what i am used to, from way back the AtariST time uptil now.
Here it is possible to copy a part (as its called) that has its volume line and pan etc. on under the part on a seperate track, and paste it all somewhere else. Easy and fast.

I do see that Blue and apparently Ardour have a different design, in that the Automation Lines are not directly connected to the SoundObject.
How does that work with the automatic start and end points? Are they after this action, connected?

Or
it might be possible to select Automation points AND SoundObject, when in MultiLine Mode? 

I do not understand why it is not possible to copy Automation Line points and their respective distances and copy these elsewhere?

**Comment by kunstmusik** [comment]
Oops, I mistyped.  I meant to say "For the start/end points issue, because I would not always want to automatically add points, what do you think about if I added an action that would add the points."

For example, if I have a long automation that controls volume or a filter cutoff, and multiple soundObjects are used within that automation, I may want to adjust the objects, but do not want to adjust the automation.  In that case, the existing behavior is fine. 

The reason for a separate action is that it would then allow the behavior you requested, but would require to press a shortcut.  This would then allow both kinds of working with the score to work.  At least, that is the rationale behind what I'm proposing with the non-automatic option to insert the points. 

Maybe another option is to create a new mode or score timeline option. Let's say the latter: what if I add a checkbox to the Score Timeline options (the panel that opens up when you press the arrow near the top-right of the score timeline), one that says something like "Link automation points with ScoreObjects". When disabled, the current behavior happens. When enabled, selecting and moving a SoundObject or AudioClip would also drag along any existing points, as well as automatically add start/end points. Copy/paste in the Score mode could also respect that option (with some caveats, listed below). 

With Blue, the SoundObject system is different than Ardour, but the AudioLayer system is similar.  Fades in the AudioLayer system are associated tot he AudioClip, just as Region Fades are with Regions in Ardour.  But with SoundObjects, there is not a 1:1 correspondence between layers and mixer channels as they are in Ardour and other MIDI-based DAW software.  

For MultiLine mode, I'm confused by your comment. I can make a selection and move both SoundObjects and automation points already.  

Copying/pasting is a curious one as it requires that the paste must be done exactly into the same layers as previously, and the layers must not have changed as well as enabled automations.  This is so that the automation data can go into the correct place.  

So, back to copy/paste.  For the paste action, if I add the "Link" option,  I imagine the following happening:

1. Check that the layer structure hasn't changed.
2. Paste objects into layers.
3. Remove existing automation points within the time span of the paste.
4. Paste automation points.

Does that match what you would expect?

**Comment by tjingboem** [comment]
>For MultiLine mode, I'm confused by your comment. I can make a selection and move both >SoundObjects and automation points already.

yes, but i thought it would be a good place to add the start and end points, being a part of Automation Lines (= Multi Lines)...seemed like to 'logical' place
but i see your point about moving some Objects without touching the Volume Line for example:
>For example, if I have a long automation that controls volume or a filter cutoff, and multiple >soundObjects are used within that automation, I may want to adjust the objects, but do not want to >adjust the automation. In that case, the existing behavior is fine.

By "the Score Timeline options", you mean the Snap function?

And i understand that the Automation Lines generate new and separate Csound Instruments; i have no idea how different Csound instruments, like a "real" instrument (b64 for example) and the for the user invisible Automation Line instrument could be linked - sorry.

>Copying/pasting is a curious one as it requires that the paste must be done exactly into the same >layers as previously, and the layers must not have changed as well as enabled automations. This is  > so that the automation data can go into the correct place.

I always paste right after i copy :)
I could be happy with pasting an Object only on its own Layer...

![screenshot from 2016-08-22 22 06 57](https://cloud.githubusercontent.com/assets/6670911/17869736/ee9181e4-68b4-11e6-953e-1addacc22b1c.png)

Here, if i wanted to copy and paste the second Instrument 1 Object, would that be possible to Link start and end points to it and paste it somewhere on that same Layer?
Then, at a later time when i want to copy and paste the 3rd Object on the 3rd Layer, could i:
- make the Automation Line visible there and
- copy/paste the 3rd Object with start and end Points on that 3rd Layer?

**Comment by kunstmusik** [comment]
Yes, the area by the snap options is the one I was thinking about. 

I think there's a disconnect in our communication. :)  The issue is not that one would have to paste only for a single object to a layer, but that any pasted objects should be pasted to the same layer they originally came from.  

I think at this point, it might be best if I just gave this a try and we have something you can experiment with and try.  It might be easier to discuss once a working version is available. I'll give it a go now and let's continue discussion after there is something to test. :)

**Comment by kunstmusik** [comment]
I got a bit stifled by this issue as there's a number of conditions.  For the meanwhile, I have moved this to 2.7.0 to get 2.6.1 out the door sooner and give more time to plan out the features for this ticket. (We can test using 2.7.0 test builds once I can implement parts.)

Some thoughts regarding this issue and different Score modes:

* I have a branch where I started this work and it has the "Link Automations to ScoreObjects" option.  What I imagine is that this would only be used in the standard Score mode.  When selected, what would happen is that:
  * Dragging SoundObjects will drag automation points.  New points will be created at start/end boundaries of each SoundObject if none already exist, and points will be duplicated outside of the boundaries of SoundObjects to preserve curves. 
  * Copying will copy automation values.  Pasting will only work if the structure of the layers is the same in the paste location. Essentially it will just use the same source and destination layers and overwrite automations while pasting copies of ScoreObjects.
  * Scaling ScoreObjects (i.e., dragging left or right to modify the duration of the object) will also scale the automation points when "Link" is enabled.
* When "Link to Automations" is not selected, the current behavior will continue as-is.  This allows users to modify objects without adjusting automations if desired.

* For Single-Line mode, adding a copy and paste feature should be fairly straight forward.  It would use the current selection system with ctrl-c to copy and ctrl-click for paste. 

* For Multi-line mode, adding a copy and paste feature should be fairly straight forward. It too would reuse the current selection system and use ctrl-c to copy and ctrl-click to paste. 

I think this would cover the various modes and scenarios.  Please chime in with further comments if I've missed something.

**Comment by tjingboem** [comment]
can Automation Line points be adapted/changed once they are copied?

**Comment by tjingboem** [comment]
on the topic of copying, i was looking at a recent video on Ardour and at 40.33 some copying was done.
address: https://www.youtube.com/watch?v=axtVERiqUIw
Perhaps you can copy some code there to paste in Blue?

**Comment by tjingboem** [comment]
cloased as this is taken care off
