### ISSUE TITLE
nGen double values

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#345]
a screenshot of how nGen, called from Blue, produces the right score values (the temp .sco file) but imported back in Blue, the score file is imported with double values at the end of the score.
![double](https://cloud.githubusercontent.com/assets/6670911/21467774/1faf9b94-c9f9-11e6-85a6-9badeed8f2f5.png)
Here, i have set the scaling of the nGen file to the same duration of nGen text output.

There are other things that are not correct when importing the temp score file but this is the first one.

PS. i have investigated this issue some more. The temporary txt file is produced ok, also the temporary .sco file as produced by nGen. Things go wrong only with the last 2 values. Rightly produced in the temp sco file, wrongly imported in the sco window of Blue. The doubling of the last 2 data do some kind of multiplying, but only on p2 and p3 - and this happens wrongly only when the Object is scaled other than the temp sco file times. 

Example: 
.....
i1   38.000  1.000     0.500   246.94165     1.035    -1.283    10.000 
i1   39.000  1.000     0.500   246.94165    -1.772    -1.559    10.000 
in the temp sco file
then imported back into Blue but rescaled to the Object's duration (20 seconds):
.....
i1	19.0	0.5	0.500	246.94165	1.035	-1.283	10.000
i1	9.75	0.25	0.500	246.94165	-1.772	-1.559	10.000
i1	9.75	0.25	0.500	246.94165	-1.772	-1.559	10.000

**Comment by kunstmusik** [comment]
I found that the score parsing code in Blue had a bug where it would repeat a note when a score statement other than comment or i-statement was found.  In this case, the nGen score generates an 'e' at the end which triggered the problem.  I have fixed this issue which seems to have cleared up the duplicated note and the odd time scaling. There are still some precision differences, but since 2.7.0 has moved to using doubles for internal processing, the differences are smaller. The latest dev build at http://www.kunstmusik.com/blue_2.7.0_dev.zip has been updated with these changes.
