### ISSUE TITLE
Code editor does not work on Windows

### ISSUE THREAD

**Issue by gogins** [kunstmusik/blue#371]
It is not possible to insert lines between lines, to backspace and delete characters, or to visibly extend a selection in the code editor for the JavaScriptObject and the instrument editor. Possibly the problem exists in the NetBeans code editor.

**Comment by kunstmusik** [comment]
I saw something like this happen with someone at the workshop. It seemed
like the config folder for Blue got corrupted somehow. Could you try:

1. In Blue, go to "About" under "Help" menu
2. Look for the setting for user directory. Mine shows:

*User directory:* C:\Users\stevenyi\AppData\Roaming\.blue\dev


3. Close Blue. Go to the reported folder in Explorer and try moving the dev
folder out of the way.

4. Restart Blue.  All settings will be reset.


I don't know the exact reason for this as I haven't seen this on my own
system, but I suspected a one time issue due to maybe having different Blue
versions over time.  What I saw with the workshop participant was that
after clearing the dev folder and starting again, all was working as
expected.

**Comment by gogins** [comment]
Thanks for getting back to me so quickly, I'll do as you suggest.

Best, Mike

**Comment by kunstmusik** [comment]
Hope it works! I'm transferring in Panama at the moment and will be away
from computer most of tomorrow, but I'll try to reply to anything that
comes up as soon as I can.

Thanks!
Steven

**Comment by gogins** [comment]
The workaround of moving the dev directory solved the problem for me. I had installed an earlier version of blue and it seems likely that was the cause of the problem.

**Comment by kunstmusik** [comment]
Glad that worked!  I'll sort of leave it here then in terms of looking
further into it.  If it pops up again, at least I'll know where to look.
Thanks!
