### ISSUE TITLE
empty space with Dropdown Menu

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#383]
using the Dropdown menu with AutomationAllowed set to Off, have the possibility to give the "Name" to  the Value "  ", so an empty space.

**Comment by tjingboem** [comment]
i have not encountered any more problems since i started over my nGen score generator project - it uses the Dropdown Menu that sometimes must insert * nothing*  (= nearly empty string, ie. 2 spaces)  instead of text
It all seems to work now, so i think you can close down this issue? Unless you want to have a closer look at the issue of course.

**Comment by kunstmusik** [comment]
I tried this with a dropdown in both ObjectBuilder and BlueSynthBuilder.  Both places I was able to use a completely empty value as well as single-space for Values for items. (I will send you a copy of this file over email.) Otherwise, I think it is working here and I can not reproduce the problem.  I will close this now, but if you come across this issue again and have a file I can use to test, that would be great.
