### ISSUE TITLE
BSB Vertical Slider Bank not scaled properly

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#427]
On Linux, the Vertical and Horizontal Slider Bank do not retain their sliderwidth. For example, using the Banks in effects and loading the effects in the Mixer, the Banks go back to their default (150) width setting and not the width as set manually in the Effect Library

**Comment by kunstmusik** [comment]
I tested and, unless I'm doing something differently, things seem to work here. I am wondering if this is an issue where you were modifying the Effect Library copy of an effect, but expecting it to change the instance that is in the mixer?  When you add an effect from the library to the mixer, it is making a unique copy that becomes standalone. You can modify and edit the mixer copy, or modify and edit the library version, but neither will affect each other. 

If this isn't the case, could you tell me steps to follow so that I can reproduce the issue?

**Comment by tjingboem** [comment]
i tried again and the issue persists. Tried to get the same bad result in an Instrument but only the effect seems to be effected :)
What i do:
1. i edit and scale  the bank in the effect
2. close the effect Library
3. throw the new effect in an empty mixerstrip
4. now the bank is not scaled anymore

Same issue for Horizontal ánd Vertical Banks. Not for the normal Slider.
