### ISSUE TITLE
Navigator: part of the project so window size and position is saved

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#504]
the state and size of open windows are saved when closing the project and they all reopen when i reopen the project, all but the Navigator. 
Can this be a setting that is part of the saved project? 
So that Navigator reopens the way the project was saved

**Comment by kunstmusik** [comment]
I'm curious about this one. I would expect the Score Navigator to have its visibility settings be part of the program settings rather than part of the project.  For example, in Reaper, if I open the navigator and then switch projects, the navigator location is stable and remains as part of the program and does not change per project.  I think I would prefer the current behavior as it makes sense to me, i.e., if I move between computers with different monitor resolutions, the saved setting for the navigator might not make sense.

**Comment by tjingboem** [comment]
Yes- i think my thoughts were simpler when i dealt with Navigator and saving a Project.
I worked  a lot with Cubase years ago, and when i opened the Project i was working on, i got all windows, window settings and locators and everything as i left it- and saved it.

That is what i looking for in Blue; the Navigator, that i have open as default, is gone when i re-open my Project.
So is the place i was working on and Blue starts at 0. This is not a big deal, when i press G i am at the right place i was before...
But i have to re-open the Navigator every time, and was wanting to have this opened the way i saved it.

**Comment by kunstmusik** [comment]
I think this isn't clearing things up for me since you didn't really address the issue. I think this needs to be more clearly understood:

1. The location/size/visibility of the navigator window is not saved with the *project* and I do not think it should be as noted above. 
2. The location/size/visibility of the navigator window should be saved with the *program* so that if you close Blue and reopen Blue, the navigator re-appears if previously opened and returned to the same location.

I do not think it makes sense to switch projects and have the navigator move around, and saving window settings doesn't respect user settings (i.e., if someone else opens up my project, it should not alter their window setup).  

If you want #1, then I have to say I am not in support and can close this issue. If you want #2 above and it is not currently working, then it's a bug and I can address that.
