### ISSUE TITLE
PatternObject has no TEST button

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#697]
The PatternObject lacks the presence of the TEST button, to preview the score generation.

**Comment by kunstmusik** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1622139/183267322-7eb71b8a-9bd1-4fdf-849c-b3b05cc30398.png">
 
I added the test button to the slide out panel on the right so that it wasn't in the way when using the object normally. I figured it would be useful on occasion but wouldn't be necessary for regular usage and would take up UI space unnecessarily. Hope this works for you @tjingboem. :)
