### ISSUE TITLE
Dropdown Menu takes up more space

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#719]
With FlatLaf the Dropdown Menu takes up more space.
![Screenshot from 2023-01-12 11-46-16](https://user-images.githubusercontent.com/6670911/212123566-901b2286-b9f3-4b8b-88d8-3a941d19cc53.png)

**Comment by DevCharly** [comment]
This is because in FlatLaf the JComboBox has a minimum width of 72px by default.

You can disable minimum width for all combo boxes with e.g.:
~~~java
UIManager.put( "ComboBox.minimumWidth", 0 );
~~~

of for single combo box with:
~~~java
myComboBox.putClientProperty( "JComponent.minimumWidth", 0 );
~~~

**Comment by kunstmusik** [comment]
Thank you very much @DevCharly for the guidance!
